// src/constants/roles.ts
import { AUTH } from './authority';

export const ROLES = {
  EMPRESA_ADMIN: [
    AUTH.DASH_EMPRESA,
    AUTH.SUBEMPRESA_CRUD,
    AUTH.SUCURSAL_CRUD,
    AUTH.EMPLEADOS_CRUD,
    AUTH.COTIZACIONES_CRUD,
  ],
  SUBEMPRESA_ADMIN: [
    AUTH.DASH_SUBEMPRESA,
    AUTH.SUCURSAL_CRUD,
    AUTH.EMPLEADOS_CRUD,
    AUTH.COTIZACIONES_CRUD,
  ],
  SUCURSAL_ADMIN: [
    AUTH.DASH_SUCURSAL,
    AUTH.EMPLEADOS_CRUD,
    AUTH.COTIZACIONES_READ,
  ],
  EMPLEADO: [
    AUTH.COTIZACIONES_READ,
  ],
} as const;
