// src/constants/roles.ts
import { AUTH } from './authority';

export const ROLES = {
  EMPRESA_ADMIN: [
    AUTH.PRODUCTOS_CRUD,
    AUTH.USUARIOS_READ,
    AUTH.USUARIOS_INVITE,
    AUTH.ORG_SUBEMPRESA,
    AUTH.ORG_SUCURSAL,
    AUTH.COTIZACIONES_CRUD,
    AUTH.ORG_SUBEMPRESA,
  ],
  SUBEMPRESA_ADMIN: [
    AUTH.ORG_SUCURSAL,
    AUTH.USUARIOS_READ,
    AUTH.COTIZACIONES_CRUD,
  ],
  SUCURSAL_ADMIN: [
    AUTH.EMPLEADOS_READ,     // si lo defines
    AUTH.COTIZACIONES_READ,
  ],
  EMPLEADO: [
    AUTH.COTIZACIONES_READ,
  ],
} as const;
