import { IItem } from '@/interface/technicalReviews.interface';

export const EQUIPMENT_TYPE_LABELS: Record<string, string> = {
	notebook: 'Notebook',
	desktop: 'Desktop',
	aio: 'All-in-One',
	docking: 'Docking',
	monitor: 'Monitor',
};

export const CONDITION_VALUES_ES: Record<string, string> = {
	like_new: 'Como Nuevo',
	good_condition: 'Buen Estado',
	good_shape: 'Buen Estado',
	visible_wear: 'Desgaste Visible',
	noticeable_wear: 'Desgaste Notable',
	needs_repair: 'Requiere Reparación',
	scrap: 'Solo Repuestos',
	ok: 'Buen Estado',
	minor_wear: 'Detalles Leves',
	worn: 'Desgastado',
	missing_pieces: 'Piezas Faltantes',
	scratched: 'Rayado',
	broken: 'Roto',
	damaged: 'Dañado',
	dead_pixels: 'Píxeles Muertos',
	screen_burn: 'Quemadura de Pantalla',
	flickering: 'Parpadeo',
	spots: 'Manchas',
	buen_estado: 'Buen Estado',
	cable_en_mal_estado: 'Cable en Mal Estado',
	damaged_cable: 'Cable en Mal Estado',
	no_corresponde_a_equipo: 'No Corresponde al Equipo',
	not_matching_equipment: 'No Corresponde al Equipo',
	no_incluye: 'No Incluye',
	not_included: 'No Incluye',
	broken_charger: 'Cargador Roto',
	broken_port: 'Entrada Rota',
	broken_ports: 'Puertos Rotos',
	light_scratches: 'Rayas Leves',
	no_stand: 'Sin Base',
	excellent: 'Excelente',
	good: 'Bueno',
	fair: 'Aceptable',
	poor: 'Pobre',
	no_battery: 'Sin Batería',
	hdd: 'HDD',
	ssd: 'SSD',
	m2: 'M.2',
	nvme: 'NVMe',
	hybrid: 'Híbrido',
	es: 'ES',
	us: 'US',
	latam: 'Latinoamericano',
	spanish: 'ES',
	english: 'US',
	latin_american: 'ES',
	international: 'US',
	working: 'Funcionando',
	not_working: 'No Funciona',
	partially_working: 'Funciona Parcialmente',
	functional: 'Funcional',
	non_functional: 'No Funcional',
	original: 'Original',
	generic: 'Genérico',
	missing: 'Faltante',
	pending: 'Pendiente',
	in_progress: 'En Progreso',
	in_review: 'En Revisión',
	reviewed: 'Revisado',
	completed: 'Completado',
	approved: 'Aprobado',
	rejected: 'Rechazado',
	received: 'Ingresado',
	available_for_sale: 'Disponible para Venta',
	in_quotation: 'En Cotización',
	reserved: 'Reservado',
	sold: 'Vendido',
	in_repair: 'En Reparación',
	scrapped: 'Dado de Baja',
	returned: 'Devuelto',
	a: 'A',
	b: 'B',
	c: 'C',
	m: 'M',
	yes: 'SI',
	no: 'NO',
	na: 'N/A',
	none: 'Ninguno',
	unknown: 'Desconocido',
	new: 'Nuevo',
	used: 'Usado',
	refurbished: 'Reacondicionado',
	scratches: 'Rayones',
	dents: 'Abolladuras',
	cracks: 'Grietas',
};

export type ExcelColDef = { header: string; key: string };

export const EXCEL_COLUMNS: Record<string, ExcelColDef[]> = {
	notebook: [
		{ header: 'Marca', key: 'brand' },
		{ header: 'Modelo', key: 'model' },
		{ header: 'Linea', key: 'line' },
		{ header: 'Serial Number', key: '__serial' },
		{ header: 'Procesador', key: 'processor' },
		{ header: 'RAM', key: 'ram_size' },
		{ header: 'Slot Ram', key: 'ram_slots' },
		{ header: 'Tipo RAM', key: 'ram_type' },
		{ header: 'HDD', key: 'storage_size' },
		{ header: 'Tec. HDD', key: 'storage_technology' },
		{ header: 'Incluye', key: 'includes_charger' },
		{ header: 'Estado', key: 'charger_status' },
		{ header: 'VGA', key: 'vga_ports' },
		{ header: 'HDMI', key: 'hdmi_ports' },
		{ header: 'Displayport', key: 'displayport_ports' },
		{ header: 'USB', key: 'usb_a_ports' },
		{ header: 'USB Tipo C', key: 'usb_c_ports' },
		{ header: 'Biometrico', key: 'has_biometric' },
		{ header: 'SD', key: 'lector_de_tarjetas_sd' },
		{ header: 'WiFi', key: 'has_wifi' },
		{ header: 'RJ-45', key: 'rj45_ports' },
		{ header: 'Bluetooth', key: 'has_bluetooth' },
		{ header: 'Pulgadas Pant.', key: 'screen_inches' },
		{ header: 'Estado Pantalla', key: 'screen_condition' },
		{ header: 'Tactil', key: 'is_touchscreen' },
		{ header: 'Estado Teclado', key: 'keyboard_condition' },
		{ header: 'ES/US', key: 'keyboard_layout' },
		{ header: 'Numerico', key: 'has_numeric_keypad' },
		{ header: 'Retroluminado', key: 'has_backlit_keyboard' },
		{ header: 'Estado Padmouse', key: 'touchpad_condition' },
		{ header: 'Estado Cubierta', key: 'cover_condition' },
		{ header: 'Estado Bisagras', key: 'hinge_condition' },
		{ header: 'Estado Inferior', key: 'bottom_condition' },
		{ header: 'Estado Bateria', key: 'battery_status' },
		{ header: 'Observaciones', key: 'observations' },
		{ header: 'CATEGORIA', key: '__grade' },
		{ header: 'S.O', key: 'operating_system' },
		{ header: 'CLIENTE', key: '__customer' },
		{ header: 'PROVEEDOR', key: '__supplier' },
		{ header: 'Codigo de Barras', key: '__barcode' },
		{ header: 'Creado por', key: '__created_by' },
		{ header: 'Revisado por', key: '__reviewed_by' },
	],
	aio: [
		{ header: 'Marca', key: 'brand' },
		{ header: 'Modelo', key: 'model' },
		{ header: 'Linea', key: 'line' },
		{ header: 'Serial Number', key: '__serial' },
		{ header: 'Procesador', key: 'processor' },
		{ header: 'RAM', key: 'ram_size' },
		{ header: 'Slot Ram', key: 'ram_slots' },
		{ header: 'Tipo RAM', key: 'ram_type' },
		{ header: 'HDD', key: 'storage_size' },
		{ header: 'Tec. HDD', key: 'storage_technology' },
		{ header: 'Incluye', key: 'includes_charger' },
		{ header: 'Estado', key: 'charger_status' },
		{ header: 'VGA', key: 'vga_ports' },
		{ header: 'HDMI', key: 'hdmi_ports' },
		{ header: 'Displayport', key: 'displayport_ports' },
		{ header: 'USB', key: 'usb_a_ports' },
		{ header: 'USB Tipo C', key: 'usb_c_ports' },
		{ header: 'SD', key: 'lector_de_tarjetas_sd' },
		{ header: 'WiFi', key: 'has_wifi' },
		{ header: 'RJ-45', key: 'rj45_ports' },
		{ header: 'Bluetooth', key: 'has_bluetooth' },
		{ header: 'Pulgadas Pant.', key: 'screen_inches' },
		{ header: 'Estado Pantalla', key: 'screen_condition' },
		{ header: 'Estado Cubierta', key: 'cover_condition' },
		{ header: 'Lector CD', key: 'has_cd_drive' },
		{ header: 'S.O', key: 'operating_system' },
		{ header: 'Observaciones', key: 'observations' },
		{ header: 'Cliente', key: '__customer' },
		{ header: 'Proveedor', key: '__supplier' },
		{ header: 'Codigo de Barras', key: '__barcode' },
		{ header: 'CATEGORIA', key: '__grade' },
		{ header: 'Creado por', key: '__created_by' },
		{ header: 'Revisado por', key: '__reviewed_by' },
	],
	desktop: [
		{ header: 'Marca', key: 'brand' },
		{ header: 'Modelo', key: 'model' },
		{ header: 'Linea', key: 'line' },
		{ header: 'Serial Number', key: '__serial' },
		{ header: 'Procesador', key: 'processor' },
		{ header: 'RAM', key: 'ram_size' },
		{ header: 'Slot Ram', key: 'ram_slots' },
		{ header: 'Tipo RAM', key: 'ram_type' },
		{ header: 'HDD', key: 'storage_size' },
		{ header: 'Tec. HDD', key: 'storage_technology' },
		{ header: 'VGA', key: 'vga_ports' },
		{ header: 'HDMI', key: 'hdmi_ports' },
		{ header: 'Displayport', key: 'displayport_ports' },
		{ header: 'USB', key: 'usb_a_ports' },
		{ header: 'USB Tipo C', key: 'usb_c_ports' },
		{ header: 'SD', key: 'lector_de_tarjetas_sd' },
		{ header: 'RJ-45', key: 'rj45_ports' },
		{ header: 'WiFi', key: 'has_wifi' },
		{ header: 'Bluetooth', key: 'has_bluetooth' },
		{ header: 'CD', key: 'has_cd_drive' },
		{ header: 'Incluye', key: 'includes_charger' },
		{ header: 'Estado', key: 'charger_status' },
		{ header: 'S.O', key: 'operating_system' },
		{ header: 'CATEGORIA', key: '__grade' },
		{ header: 'Observaciones', key: 'observations' },
		{ header: 'Cliente', key: '__customer' },
		{ header: 'Proveedor', key: '__supplier' },
		{ header: 'Codigo de Barras', key: '__barcode' },
		{ header: 'Creado por', key: '__created_by' },
		{ header: 'Revisado por', key: '__reviewed_by' },
	],
	docking: [
		{ header: 'Marca', key: 'brand' },
		{ header: 'Modelo', key: 'model' },
		{ header: 'Serial Number', key: '__serial' },
		{ header: 'Incluye', key: 'includes_charger' },
		{ header: 'Estado', key: 'charger_status' },
		{ header: 'HDMI', key: 'hdmi_ports' },
		{ header: 'Displayport', key: 'displayport_ports' },
		{ header: 'USB', key: 'usb_a_ports' },
		{ header: 'RJ-45', key: 'rj45_ports' },
		{ header: 'USB Tipo C', key: 'usb_c_ports' },
		{ header: 'Creado por', key: '__created_by' },
		{ header: 'Revisado por', key: '__reviewed_by' },
	],
	monitor: [
		{ header: 'Marca', key: 'brand' },
		{ header: 'Modelo', key: 'model' },
		{ header: 'Serial Number', key: '__serial' },
		{ header: 'Pulgadas Pant.', key: 'screen_inches' },
		{ header: 'Estado Pantalla', key: 'screen_condition' },
		{ header: 'Alimentación', key: 'includes_power_cable' },
		{ header: 'Estado del Cable', key: 'power_cable_status' },
		{ header: 'Observaciones', key: 'observations' },
		{ header: 'Cliente', key: '__customer' },
		{ header: 'Proveedor', key: '__supplier' },
		{ header: 'Codigo de Barras', key: '__barcode' },
		{ header: 'Creado por', key: '__created_by' },
		{ header: 'Revisado por', key: '__reviewed_by' },
	],
};

export type ExcelGroupDef = { label: string; color: string; span: number };

export const EXCEL_GROUPS: Record<string, ExcelGroupDef[]> = {
	notebook: [
		{ label: 'Nº', color: '305496', span: 1 },
		{ label: 'Identificación', color: '4472C4', span: 4 },
		{ label: 'Hardware', color: '548235', span: 6 },
		{ label: 'Cargador', color: 'BF8F00', span: 2 },
		{ label: 'Puertos', color: '7030A0', span: 10 },
		{ label: 'Pantalla', color: 'C65911', span: 3 },
		{ label: 'Teclado', color: '00B050', span: 4 },
		{ label: 'Padmouse', color: 'FF6600', span: 1 },
		{ label: 'Carcasa - Bisagras - Otros', color: '4BACC6', span: 3 },
		{ label: 'Batería', color: 'FF4444', span: 1 },
		{ label: 'Notas', color: '808080', span: 1 },
		{ label: 'Clasificación', color: 'C00000', span: 5 },
	],
	aio: [
		{ label: 'Nº', color: '305496', span: 1 },
		{ label: 'Identificación', color: '4472C4', span: 4 },
		{ label: 'Hardware', color: '548235', span: 6 },
		{ label: 'Cargador', color: 'BF8F00', span: 2 },
		{ label: 'Puertos', color: '7030A0', span: 9 },
		{ label: 'Pantalla', color: 'C65911', span: 2 },
		{ label: 'Carcasa - Otros', color: '4BACC6', span: 2 },
		{ label: 'Software / Notas', color: '808080', span: 2 },
		{ label: 'Clasificación', color: 'C00000', span: 4 },
	],
	desktop: [
		{ label: 'Nº', color: '305496', span: 1 },
		{ label: 'Identificación', color: '4472C4', span: 4 },
		{ label: 'Hardware', color: '548235', span: 6 },
		{ label: 'Puertos', color: '7030A0', span: 9 },
		{ label: 'Otros', color: '4BACC6', span: 1 },
		{ label: 'Cargador', color: 'BF8F00', span: 2 },
		{ label: 'Software', color: '808080', span: 1 },
		{ label: 'Clasificación', color: 'C00000', span: 5 },
	],
	docking: [
		{ label: 'Nº', color: '305496', span: 1 },
		{ label: 'Identificación', color: '4472C4', span: 3 },
		{ label: 'Cargador', color: 'BF8F00', span: 2 },
		{ label: 'Puertos', color: '7030A0', span: 5 },
	],
	monitor: [
		{ label: 'Nº', color: '305496', span: 1 },
		{ label: 'Identificación', color: '4472C4', span: 3 },
		{ label: 'Pantalla', color: 'C65911', span: 2 },
		{ label: 'Cable', color: 'BF8F00', span: 2 },
		{ label: 'Notas', color: '808080', span: 1 },
		{ label: 'Clasificación', color: 'C00000', span: 3 },
	],
};
