/**
 * notebook.fields.ts
 * Source of truth for field definitions, groups, and validation hints.
 * Used by useFormCompleteness hook.
 */

export const NOTEBOOK_FIELDS_METADATA = {
	brand: {
		type: 'string',
		label: 'Marca',
		group: 'Identificación',
		hint: 'Fabricante del equipo (Dell, HP, Lenovo, etc.)',
	},
	model: {
		type: 'string',
		label: 'Modelo',
		group: 'Identificación',
		hint: 'Modelo exacto del equipo para referencia y compatibilidad',
	},
	general_condition: {
		type: 'string',
		label: 'Condición general',
		group: 'Condición',
		allowed_values: ['like_new', 'good_shape', 'visible_wear', 'needs_repair', 'scrap'],
		hint: 'Estado general del equipo considerando estética y funcionamiento global',
	},
	observations: {
		type: 'string',
		label: 'Observaciones',
		group: 'Notas',
		hint: 'Notas libres relevantes encontradas durante la revisión',
	},
	processor: {
		type: 'string',
		label: 'Procesador',
		group: 'Hardware',
		hint: 'Modelo de CPU (ej: Intel i5-8250U, Ryzen 5 3500U)',
	},
	ram_size: {
		type: 'string',
		label: 'RAM',
		group: 'Hardware',
		hint: 'Capacidad total de memoria RAM',
	},
	ram_slots: {
		type: 'string',
		label: 'Slots RAM',
		group: 'Hardware',
		hint: 'Formato cantidad x módulos (total x cantidad de módulos)',
	},
	ram_type: {
		type: 'string',
		label: 'Tipo de RAM',
		group: 'Hardware',
		hint: 'Tecnología de RAM soportada',
	},
	storage_size: {
		type: 'string',
		label: 'Almacenamiento',
		group: 'Hardware',
		hint: 'Capacidad de almacenamiento principal',
	},
	storage_technology: {
		type: 'string',
		label: 'Tecnología de disco',
		group: 'Hardware',
		allowed_values: ['HDD', 'SSD', 'M2', 'NVME', 'HYBRID'],
		hint: 'Tipo de unidad de almacenamiento',
	},
	includes_charger: {
		type: 'boolean',
		label: 'Incluye cargador',
		group: 'Accesorios',
		hint: 'Indica si se entrega con cargador',
	},
	charger_watts: {
		type: 'string',
		label: 'Watts cargador',
		group: 'Accesorios',
		hint: 'Potencia del cargador recomendado',
	},
	charger_status: {
		type: 'string',
		label: 'Estado cargador',
		group: 'Accesorios',
		allowed_values: [
			'buen_estado',
			'cable_en_mal_estado',
			'no_corresponde_a_equipo',
			'no_incluye',
			'broken_charger',
			'broken_port',
		],
		hint: 'Condición del cargador si se incluye',
	},
	screen_inches: {
		type: 'string',
		label: 'Pulgadas pantalla',
		group: 'Pantalla',
		hint: 'Tamaño de la pantalla en pulgadas',
	},
	screen_condition: {
		type: 'string',
		label: 'Condición de pantalla',
		group: 'Pantalla',
		allowed_values: [
			'ok',
			'minor_wear',
			'worn',
			'missing_pieces',
			'dead_pixels',
			'broken',
			'spots',
		],
		hint: 'Estado físico/visual del panel',
	},
	cover_condition: {
		type: 'string',
		label: 'Tapa superior',
		group: 'Carcasa',
		allowed_values: ['ok', 'minor_wear', 'worn', 'missing_pieces', 'scratched', 'broken'],
		hint: 'Estado de la cubierta/tapa superior del equipo',
	},
	keyboard_condition: {
		type: 'string',
		label: 'Teclado',
		group: 'Carcasa',
		allowed_values: ['ok', 'worn', 'missing_pieces', 'broken'],
		hint: 'Estado del teclado',
	},
	keyboard_layout: {
		type: 'string',
		label: 'Distribución teclado',
		group: 'Carcasa',
		allowed_values: ['es', 'us', 'latam'],
		hint: 'Layout físico del teclado',
	},
	hinge_condition: {
		type: 'string',
		label: 'Bisagras',
		group: 'Carcasa',
		allowed_values: ['ok', 'worn', 'missing_pieces', 'broken'],
		hint: 'Estado de las bisagras de apertura/cierre',
	},
	battery_health: {
		type: 'string',
		label: 'Health batería',
		group: 'Batería',
		hint: 'Texto o porcentaje informado por el sistema',
	},
	battery_status: {
		type: 'string|integer',
		label: 'Estado batería',
		group: 'Batería',
		allowed_values: ['excellent', 'good', 'fair', 'poor', 'no_battery'],
		hint: 'Porcentaje o categoría',
	},
	has_second_battery: {
		type: 'boolean',
		label: 'Segunda batería',
		group: 'Batería',
		hint: 'Indica si el equipo trae una segunda batería',
	},
	second_battery_status: {
		type: 'string',
		label: 'Estado 2ª batería',
		group: 'Batería',
		allowed_values: ['excellent', 'good', 'fair', 'poor', 'no_battery'],
		hint: 'Estado de la segunda batería (mismas opciones que la principal)',
	},
	second_battery_percentage: {
		type: 'integer',
		label: 'Porcentaje 2ª batería',
		group: 'Batería',
		min: 0,
		hint: 'Porcentaje de salud de la segunda batería',
	},
	second_battery_condition: {
		type: 'string',
		label: 'Condición 2ª batería',
		group: 'Batería',
		hint: 'Texto o porcentaje informado de la segunda batería',
	},
	vga_ports: {
		type: 'integer',
		label: 'Puertos VGA',
		group: 'Puertos',
		min: 0,
	},
	hdmi_ports: {
		type: 'integer',
		label: 'Puertos HDMI',
		group: 'Puertos',
		min: 0,
	},
	displayport_ports: {
		type: 'integer',
		label: 'Puertos DisplayPort',
		group: 'Puertos',
		min: 0,
	},
	usb_c_ports: {
		type: 'integer',
		label: 'Puertos USB-C',
		group: 'Puertos',
		min: 0,
	},
	sd_readers: {
		type: 'integer',
		label: 'Lectores SD',
		group: 'Puertos',
		min: 0,
	},
	rj45_ports: {
		type: 'integer',
		label: 'Puertos RJ45',
		group: 'Puertos',
		min: 0,
	},
	all_ports_functional: {
		type: 'boolean',
		label: 'Todos los puertos funcionales',
		group: 'Puertos',
		hint: 'Marca si todos los puertos probados funcionan correctamente',
	},
	usb_a_ports: {
		type: 'integer',
		label: 'Puertos USB-A',
		group: 'Puertos',
		min: 0,
	},
	defective_ports_count: {
		type: 'integer',
		label: 'Puertos defectuosos',
		group: 'Puertos',
		min: 0,
		hint: 'Cantidad de puertos dañados',
	},
	has_biometric: {
		type: 'boolean',
		label: 'Biométrico',
		group: 'Otros',
		hint: 'Incluye lector de huellas o cámara IR',
	},
	has_wifi: {
		type: 'boolean',
		label: 'WiFi',
		group: 'Otros',
	},
	has_bluetooth: {
		type: 'boolean',
		label: 'Bluetooth',
		group: 'Otros',
	},
	is_touchscreen: {
		type: 'boolean',
		label: 'Pantalla táctil',
		group: 'Pantalla',
	},
	touchpad_condition: {
		type: 'string',
		label: 'Touchpad',
		group: 'Carcasa',
		allowed_values: ['ok', 'worn', 'missing_pieces', 'broken'],
	},
	bottom_condition: {
		type: 'string',
		label: 'Tapa inferior',
		group: 'Carcasa',
		allowed_values: ['ok', 'worn', 'missing_pieces', 'scratched', 'broken'],
	},
	has_numeric_keypad: {
		type: 'boolean',
		label: 'Teclado numérico',
		group: 'Carcasa',
	},
	has_backlit_keyboard: {
		type: 'boolean',
		label: 'Teclado retroiluminado',
		group: 'Carcasa',
	},
	operating_system: {
		type: 'string',
		label: 'Sistema operativo',
		group: 'Software',
		hint: 'SO instalado o recomendado',
	},
} as const;
