// src/config/pages.config.ts

/* =================================================
   ZENTRIA ERP - CONFIGURACIÓN DE PÁGINAS
   ================================================= */

export interface PageConfig {
	id: string;
	to: string;
	text: string;
	icon: string;
	authority: string[];
	roles?: string[];
	companyId?: number;
	requireAll?: boolean;
}

export const authPages = {
	loginPage: {
		id: 'loginPage',
		to: '/login',
		text: 'Login',
		icon: 'DuoLogOut',
		authority: [],
	},
	profilePage: {
		id: 'profilePage',
		to: '/profile',
		text: 'Perfil',
		icon: 'DuoUser',
		authority: [],
	},
	aceptarInvitacion: {
		id: 'aceptarInvitacion',
		to: '/invitar/aceptar/:token',
		text: 'Aceptar invitación',
		icon: 'DuoMailOpened',
		authority: [],
	},
	recuperarPassword: {
		id: 'recuperarPassword',
		to: '/recuperar-password',
		text: 'Recuperar contraseña',
		icon: 'DuoKey',
		authority: [],
	},
	confirmarNuevaPass: {
		id: 'confirmarNuevaPass',
		to: '/reset-password',
		text: 'Confirmar nueva contraseña',
		icon: 'DuoFile',
		authority: [],
	},
} satisfies Record<string, PageConfig>;

/* =================================================
   PÁGINAS PRIVADAS - MÓDULOS ERP
   ================================================= */

// src/config/pages.config.ts
export const privatePages = {
	dashboard: {
		id: 'dashboard',
		to: '/dashboard',
		text: 'Home',
		icon: 'DuoHomeHeart',
	},

	// =========================
	// GESTIÓN
	// =========================
	manage: {
		id: 'manage',
		to: '/gestion',
		text: 'Gestión',
		icon: 'HeroBuildingStorefront',
		authority: ['view-company'],
		roles: [
			'super-admin',
			'admin',
			'company-admin',	
			'subsidiary-admin',
			'branch-admin',
			'company-supervisor',
			'manager',
		],
		subPages: {
			company: {
				id: 'company',
				to: '/gestion/empresa',
				text: 'Empresa',
				icon: 'DuoBuilding',
				authority: ['view-company'],
				roles: [
					'super-admin',
					'admin',
					'company-admin',
					'subsidiary-admin',
					'branch-admin',
					'company-supervisor',
					'manager',
				],
			},
			subsidiary: {
				id: 'subsidiary',
				to: '/gestion/subempresa',
				text: 'Subempresa',
				icon: 'DuoBuilding',
				authority: ['view-subsidiary'],
				roles: [
					'super-admin',
					'admin',
					'company-admin',
					'subsidiary-admin',
					'branch-admin',
					'company-supervisor',
					'manager',
					'technician',
					'warehouse-employee',
					'warehouse-manager',
				],
			},
			subsidiaryDetail: {
				id: 'subsidiaryDetail',
				to: '/gestion/subempresa/:id',
				text: 'Detalle Subempresa',
				icon: 'DuoBuilding',
				authority: ['view-subsidiary'],
				roles: [
					'super-admin',
					'admin',
					'company-admin',
					'subsidiary-admin',
					'branch-admin',
					'company-supervisor',
					'manager',
					'technician',
					'warehouse-employee',
					'warehouse-manager',
				],
			},
			subsidiaryCustomization: {
				id: 'subsidiaryCustomization',
				to: '/gestion/subempresa/personalizacion',
				text: 'Personalización de Subempresa',
				icon: 'HeroPaintBrush',
				authority: ['view-subsidiary'],
				roles: [
					'super-admin',
					'admin',
					'company-admin',
					'subsidiary-admin',
					'branch-admin',
					'company-supervisor',
					'manager',
					'technician',
					'warehouse-employee',
					'warehouse-manager',
				],
			},
			branch: {
				id: 'branch',
				to: '/gestion/sucursal',
				text: 'Sucursal',
				icon: 'DuoHome',
				authority: ['view-branch'],
				roles: [
					'super-admin',
					'admin',
					'company-admin',
					'subsidiary-admin',
					'branch-admin',
					'company-supervisor',
					'manager',
					'technician',
					'warehouse-employee',
					'warehouse-manager',
				],
			},
			branchDetail: {
				id: 'branchDetail',
				to: '/gestion/sucursal/:id',
				text: 'Detalle Sucursal',
				icon: 'HeroBuildingStorefront',
				authority: ['view-branch'],
				roles: [
					'super-admin',
					'admin',
					'company-admin',
					'subsidiary-admin',
					'branch-admin',
					'company-supervisor',
					'manager',
					'technician',
					'warehouse-employee',
					'warehouse-manager',
				],
			},
			manageUsers: {
				id: 'manageUsers',
				to: '/gestion/usuarios',
				text: 'Usuarios',
				icon: 'DuoUsers',
				authority: ['view-user'],
				roles: [
					'super-admin',
					'admin',
					'company-admin',
					'subsidiary-admin',
					'branch-admin',
					'company-supervisor',
					'manager',
				],
			},
			permissionsAdmin: {
				id: 'permissionsAdmin',
				to: '/admin/permisos',
				text: 'Administrar Permisos',
				icon: 'DuoShieldCheck',
				authority: ['manage-permissions'],
				roles: ['super-admin'],
				requireAll: true,
			},
			rolesPermisos: {
				id: 'rolesPermisos',
				to: '/gestion/roles-permisos',
				text: 'Gestion de usuarios',
				icon: 'DuoGroup',
				authority: ['manage-roles', 'view-user'],
				roles: ['super-admin', 'company-admin'],
				requireAll: false,
			},
			rolesPermisosDetail: {
				id: 'rolesPermisosDetail',
				to: '/gestion/roles-permisos/:userId',
				text: 'Detalle Usuario',
				icon: 'DuoUser',
				authority: ['manage-roles', 'view-user'],
				roles: ['super-admin', 'company-admin'],
				requireAll: false,
			},
		},
	},

	// =========================
	// INVENTARIO
	// =========================
	inventory: {
		id: 'inventory',
		to: '/inventario',
		text: 'Inventario',
		icon: 'DuoBox3',
		authority: ['view-warehouse'],
		roles: [
			'super-admin',
			'admin',
			'company-admin',
			'subsidiary-admin',
			'branch-admin',
			'company-supervisor',
			'manager',
			'warehouse-employee',
			'warehouse-manager',
			'after-sales',
		],
		subPages: {
			transfers: {
				id: 'commercialTransfers',
				to: '/inventario/transferencias',
				text: 'Transferencias Comerciales',
				icon: 'HeroTruck',
				authority: ['view-transfer'],
				roles: [
					'super-admin',
					'admin',
					'company-admin',
					'subsidiary-admin',
					'branch-admin',
					'company-supervisor',
					'warehouse-manager',
				],
			},
			movements: {
				id: 'movements',
				to: '/inventario/movimientos',
				text: 'Movimientos',
				icon: 'HeroArrowsRightLeft',
				authority: [],
			},
		},
	},

	// =========================
	// COMERCIAL
	// =========================
	commercial: {
		id: 'commercial',
		to: '/comercial',
		text: 'Comercial',
		icon: 'DuoBag',
		authority: ['view-sale'],
		roles: [
			'super-admin',
			'admin',
			'company-admin',
			'subsidiary-admin',
			'branch-admin',
			'company-supervisor',
			'manager',
			'employee',
			'technician',
			'warehouse-employee',
			'warehouse-manager',
			'salesperson',
			'after-sales',
		],
		requireAll: false,
		subPages: {
			sales: {
				id: 'sales',
				to: '/comercial/ventas',
				text: 'Ventas',
				icon: 'DuoSale1',
				authority: ['view-sale'],
				roles: [
					'super-admin',
					'admin',
					'company-admin',
					'subsidiary-admin',
					'branch-admin',
					'company-supervisor',
					'manager',
					'employee',
					'technician',
					'warehouse-employee',
					'warehouse-manager',
					'salesperson',
					'after-sales',
				],
			},
			quotes: {
				id: 'quotes',
				to: '/comercial/cotizaciones',
				text: 'Cotizaciones',
				icon: 'DuoArticle',
				authority: ['view-quote'],
				roles: [
					'super-admin',
					'admin',
					'company-admin',
					'subsidiary-admin',
					'branch-admin',
					'company-supervisor',
					'manager',
					'employee',
					'technician',
					'warehouse-employee',
					'warehouse-manager',
					'salesperson',
					'after-sales',
				],
			},
			transfers: {
				id: 'commercialTransfers',
				to: '/comercial/transferencias',
				text: 'Transferencias',
				icon: 'HeroTruck',
				authority: ['view-sale'],
				roles: [
					'super-admin',
					'admin',
					'company-admin',
					'subsidiary-admin',
					'branch-admin',
					'company-supervisor',
					'manager',
					'employee',
					'technician',
					'warehouse-employee',
					'warehouse-manager',
					'salesperson',
					'after-sales',
				],
			},
			warranties: {
				id: 'warranties',
				to: '/comercial/warranties',
				text: 'Garantías',
				icon: 'DuoShieldCheck',
				authority: ['view-warranty'],
				roles: [
					'super-admin',
					'admin',
					'company-admin',
					'subsidiary-admin',
					'branch-admin',
					'company-supervisor',
					'manager',
					'technician',
					'warehouse-employee',
					'warehouse-manager',
					'salesperson',
					'after-sales',
				],
				requireAll: false,
			},
			warrantyDetail: {
				id: 'warrantyDetail',
				to: '/garantias/:warrantyId',
				text: 'Detalle de garantía',
				icon: 'DuoShieldCheck',
				authority: ['view-warranty'],
				roles: [
					'super-admin',
					'admin',
					'company-admin',
					'subsidiary-admin',
					'branch-admin',
					'company-supervisor',
					'manager',
					'technician',
					'warehouse-employee',
					'warehouse-manager',
					'salesperson',
					'after-sales',
				],
				requireAll: false,
			},
			clientesVentas: {
				id: 'clientesVentas',
				to: '/comercial/clientes-ventas',
				text: 'Clientes Ventas',
				icon: 'DuoUser',
				authority: ['view-customer-sale'],
				roles: [
					'super-admin',
					'admin',
					'company-admin',
					'subsidiary-admin',
					'branch-admin',
					'company-supervisor',
					'manager',
					'salesperson',
					'after-sales',
				],
			},
			clientesVentasDetalle: {
				id: 'clientesVentasDetalle',
				to: '/comercial/clientes-ventas/:clienteId',
				text: 'Detalle Clientes Ventas',
				icon: 'DuoUsers',
				authority: ['view-customer-sale'],
				roles: [
					'super-admin',
					'admin',
					'company-admin',
					'subsidiary-admin',
					'branch-admin',
					'company-supervisor',
					'manager',
					'salesperson',
					'after-sales',
				],
			},
		},
	},

	// =========================
	// REPORTES (GERENCIA)
	// =========================
	reports: {
		id: 'reports',
		to: '/reportes',
		text: 'Reportes',
		icon: 'DuoChart',
		authority: ['view-dashboard'],
		roles: [
			'super-admin',
			'admin',
			'company-admin',
			'subsidiary-admin',
			'branch-admin',
			'company-supervisor',
			'manager',
		],
		subPages: {
			salesDashboard: {
				id: 'salesDashboard',
				to: '/reportes/ventas',
				text: 'Dashboard de Ventas',
				icon: 'DuoPriceTag',
				authority: ['view-dashboard'],
				roles: [
					'super-admin',
					'admin',
					'company-admin',
					'subsidiary-admin',
					'branch-admin',
					'company-supervisor',
					'manager',
				],
			},
			inventoryReports: {
				id: 'inventoryReports',
				to: '/reportes/inventario',
				text: 'Reportes de Inventario',
				icon: 'DuoBox3',
				authority: ['view-reports'],
				roles: [
					'super-admin',
					'admin',
					'company-admin',
					'subsidiary-admin',
					'branch-admin',
					'company-supervisor',
					'manager',
				],
			},
			financialReports: {
				id: 'financialReports',
				to: '/reportes/financieros',
				text: 'Reportes Financieros',
				icon: 'DuoMoney',
				authority: ['view-reports', 'export-reports'],
				roles: ['super-admin', 'company-admin', 'manager'],
			},
		},
	},

	// =========================
	// INTEGRACIONES
	// =========================
	integrations: {
		id: 'integrations',
		to: '/integraciones',
		text: 'Integraciones',
		icon: 'DuoGlobe',
		authority: ['view-integration'],
		roles: ['super-admin'],
		requireAll: false,
		subPages: {
			list: {
				id: 'integrationsList',
				to: '/integraciones/lista',
				text: 'Listado',
				icon: 'DuoBulletList',
				authority: ['view-integration'],
				roles: ['super-admin'],
			},
			unmappedProducts: {
				id: 'unmappedProducts',
				to: '/integraciones/productos-sin-mapear',
				text: 'Productos Sin Mapear',
				icon: 'DuoQuestionCircle',
				authority: ['unmapped-woocommerce-products.index'],
				roles: ['super-admin'],
			},
			syncStock: {
				id: 'syncStock',
				to: '/integraciones/sincronizar-stock',
				text: 'Sincronizar Stock',
				icon: 'DuoUpdate',
				authority: ['view-integration'],
				roles: ['super-admin'],
			},
			importOrders: {
				id: 'importOrders',
				to: '/integraciones/importar-ordenes',
				text: 'Importar Órdenes',
				icon: 'DuoDownload',
				authority: ['view-integration'],
				roles: ['super-admin'],
			},
		},
	},

	// =========================
	// RECURSOS HUMANOS
	// =========================
	humanResources: {
		id: 'humanResources',
		to: '/rrhh',
		text: 'Recursos Humanos',
		icon: 'DuoGroup',
		authority: ['invite-users'],
		roles: ['super-admin', 'admin', 'company-admin', 'subsidiary-admin', 'branch-admin'],
		requireAll: false,
		subPages: {
			invitationsAdmin: {
				id: 'invitationsAdmin',
				to: '/admin/invitaciones',
				text: 'Gestionar Invitaciones',
				icon: 'DuoSend',
				authority: ['invite-users'],
				roles: [
					'super-admin',
					'admin',
					'company-admin',
					'subsidiary-admin',
					'branch-admin',
				],
				requireAll: false,
			},
		},
	},

	// =========================
	// SERVICIO TÉCNICO
	// =========================
	technical: {
		id: 'technical',
		to: '/tecnico',
		text: 'Técnico',
		icon: 'DuoTools',
		authority: ['view-technical-reviews-batches'],
		roles: [
			'super-admin',
			'admin',
			'company-admin',
			'subsidiary-admin',
			'branch-admin',
			'company-supervisor',
			'employee',
			'technician',
			'warehouse-employee',
			'warehouse-manager',
			'salesperson',
			'after-sales',
		],
		subPages: {
			reviews: {
				id: 'technicalReviews',
				to: '/technical-reviews',
				text: 'Revisiones Técnicas',
				icon: 'DuoTools',
				authority: ['view-technical-reviews-batches'],
				roles: [
					'super-admin',
					'admin',
					'company-admin',
					'subsidiary-admin',
					'branch-admin',
					'company-supervisor',
					'employee',
					'technician',
					'warehouse-employee',
					'warehouse-manager',
					'salesperson',
					'after-sales',
				],
			},
			batches: {
				id: 'technicalBatches',
				to: '/technical-reviews/batches',
				text: 'Revisiones por lotes',
				icon: 'DuoClipboard', // Using a clipboard icon
				authority: ['view-technical-reviews-batches'],
				roles: [
					'super-admin',
					'admin',
					'company-admin',
					'subsidiary-admin',
					'branch-admin',
					'company-supervisor',
					'employee',
					'technician',
					'warehouse-employee',
					'warehouse-manager',
					'salesperson',
					'after-sales',
				],
			},
		},
	},

	// =========================
	// CATÁLOGOS
	// =========================
	catalogs: {
		id: 'catalogs',
		to: '/catalogos',
		text: 'Catálogos',
		icon: 'DuoArchive',
		authority: ['view-product'],
		roles: [
			'super-admin',
			'admin',
			'company-admin',
			'subsidiary-admin',
			'branch-admin',
			'catalog-admin',
			'company-supervisor',
			'manager',
			'employee',
			'technician',
			'warehouse-employee',
			'warehouse-manager',
			'salesperson',
			'after-sales',
		],
		requireAll: false,
		subPages: {
			products: {
				id: 'products',
				to: '/catalogos/productos',
				text: 'Productos',
				icon: 'DuoPixels',
				authority: ['view-product'],
				roles: [
					'super-admin',
					'admin',
					'company-admin',
					'subsidiary-admin',
					'branch-admin',
					'catalog-admin',
					'company-supervisor',
					'manager',
					'employee',
					'technician',
					'warehouse-employee',
					'warehouse-manager',
					'salesperson',
					'after-sales',
				],
				requireAll: false,
			},
			productsDetail: {
				id: 'productsDetail',
				to: '/catalogos/productos/:productId',
				text: 'Detalle de producto',
				icon: 'DuoBox',
				authority: ['view-product'],
				roles: [
					'super-admin',
					'admin',
					'company-admin',
					'subsidiary-admin',
					'branch-admin',
					'catalog-admin',
					'company-supervisor',
					'manager',
					'employee',
					'technician',
					'warehouse-employee',
					'warehouse-manager',
					'salesperson',
					'after-sales',
				],
				requireAll: false,
			},
			warehouses: {
				id: 'warehouses',
				to: '/catalogos/bodegas',
				text: 'Bodegas',
				icon: 'DuoBarcode',
				authority: ['view-warehouse'],
				roles: [
					'super-admin',
					'admin',
					'company-admin',
					'subsidiary-admin',
					'branch-admin',
					'company-supervisor',
					'manager',
					'warehouse-employee',
					'warehouse-manager',
					'after-sales',
				],
				requireAll: false,
			},
			categories: {
				id: 'categories',
				to: '/catalogos/categorias',
				text: 'Categorías',
				icon: 'DuoBox2',
				authority: ['view-category'],
				roles: [
					'super-admin',
					'admin',
					'company-admin',
					'subsidiary-admin',
					'branch-admin',
					'catalog-admin',
					'company-supervisor',
					'manager',
					'employee',
					'salesperson',
					'after-sales',
				],
				requireAll: false,
			},
			brands: {
				id: 'brands',
				to: '/catalogos/marcas',
				text: 'Marcas',
				icon: 'DuoBox1',
				authority: ['view-brand'],
				roles: [
					'super-admin',
					'admin',
					'company-admin',
					'subsidiary-admin',
					'branch-admin',
					'catalog-admin',
					'company-supervisor',
					'manager',
					'employee',
					'salesperson',
					'after-sales',
				],
				requireAll: false,
			},
			suppliers: {
				id: 'suppliers',
				to: '/catalogos/proveedores',
				text: 'Proveedores',
				icon: 'DuoUser',
				authority: ['view-supplier'],
				roles: [
					'super-admin',
					'admin',
					'company-admin',
					'subsidiary-admin',
					'branch-admin',
					'company-supervisor',
					'manager',
				],
				requireAll: false,
			},
			customers: {
				id: 'customers',
				to: '/catalogos/clientes',
				text: 'Clientes-Proveedor',
				icon: 'DuoGroup',
				authority: ['view-customer-supplier'],
				roles: [
					'super-admin',
					'admin',
					'company-admin',
					'subsidiary-admin',
					'branch-admin',
					'company-supervisor',
					'manager',
				],
				requireAll: false,
			},
			documents: {
				id: 'documents',
				to: '/documentos',
				text: 'Documentos',
				icon: 'DuoUpload',
				authority: ['view-document'],
				roles: [
					'super-admin',
					'admin',
					'company-admin',
					'subsidiary-admin',
					'branch-admin',
					'company-supervisor',
				],
				requireAll: false,
			},
		},
	},

	// =========================
	// ADMIN SISTEMA + NOTIFS
	// (no aparecen en el aside, pero se usan en rutas/header)
	// =========================
	systemAdmin: {
		id: 'systemAdmin',
		to: '/admin',
		text: 'Administración',
		icon: 'DuoSettings',
		authority: ['access-admin-panel'],
		roles: ['super-admin', 'company-admin'],
		requireAll: false,
		subPages: {
			systemParameters: {
				id: 'systemParameters',
				to: '/admin/parametros-sistema',
				text: 'Parámetros del Sistema',
				icon: 'DuoSliders',
				authority: ['access-admin-panel'],
				roles: ['super-admin', 'company-admin'],
				requireAll: false,
			},
			systemParametersDetail: {
				id: 'systemParametersDetail',
				to: '/admin/parametros-sistema/:id',
				text: 'Detalle Parámetro',
				icon: 'DuoSliders',
				authority: ['access-admin-panel'],
				roles: ['super-admin', 'company-admin'],
				requireAll: false,
			},
		},
	},

	notifications: {
		id: 'notifications',
		to: '/notificaciones',
		text: 'Notificaciones',
		icon: 'DuoNotification',
		authority: [],
		roles: [
			'super-admin',
			'company-admin',
			'subsidiary-admin',
			'branch-admin',
			'manager',
			'employee',
			'technician',
			'cashier',
			'sales-rep',
		],
	},
};

export const pagesConfig = { ...authPages, ...privatePages };
export default pagesConfig;
